### ISSUE TITLE
Upgrading from 3.2 to 4.0

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [sabre-io/sabre.io#117]
Where can I find a description of how to update from 3.4 to 4.0?
http://sabre.io/dav/upgrading/ is out of date

**Comment by staabm** [comment]
AFAIR the only BC change was the raised php version requirement, right?

if this is the case we should also mention it in the changelog, not only the website

**Comment by DeepDiver1975** [comment]
- php min version
- due to newer event library:
![Screenshot from 2019-07-02 16-29-05](https://user-images.githubusercontent.com/1005065/60520940-918f2780-9ce6-11e9-96ad-f22aef28211a.png)
- due to newer url library:
![Screenshot from 2019-07-02 16-28-46](https://user-images.githubusercontent.com/1005065/60520941-918f2780-9ce6-11e9-9175-5a8283c04f05.png)

**Comment by evert** [comment]
It might take me a day or two but I can do a full write up. I think there's a few more subtleties

**Comment by DeepDiver1975** [comment]
- deprecation:
![Screenshot from 2019-07-02 16-30-38](https://user-images.githubusercontent.com/1005065/60521059-d3b86900-9ce6-11e9-9391-28907fee3a55.png)

**Comment by ByteHamster** [comment]
More than 2 years later, I don't really think this is relevant anymore. People have probably figured out how to update by now.
