### ISSUE TITLE
amend sabre.io/baikal/troubleshooting/

### ISSUE THREAD

**Issue by c-alpha** [sabre-io/sabre.io#83]
As of OS X 10.11 "El Capitan", the redirect for `.well-known/caldav` is no longer needed. The server path can successfully specified in when creating the CalDAV account. Only the `.well-known/carddav` redirect is needed for El Capitan, since creating CardDAV type contacts accounts is severely broken in El Capitan (10.11.3 as of this writing).

**Comment by evert** [comment]
I think it's regardless a smart idea to keep the redirects in place. It allows you to keep your setup instructions smaller (you just need the hostname).

**Comment by c-alpha** [comment]
That said, why not make it part of the default config then?
What would you think about updating the headline to say "...Yosemite _and Later_"?
I didn't need any redirects at all for Baikal 0.2.7 with Yosemite clients, btw.

**Comment by c-alpha** [comment]
Just noticed that I need the calendar redirect for iOS 9.2.1. One more incentive for making the redirects part of `html/.htaccess` by default?

**Comment by evert** [comment]
The assumption is that most people don't run a dedicated vhost for baikal. They are part of the default vhost configuration examples in the docs though. If you run baikal in a subdirectory, the `.htaccess` redirects are pointless because they only make sense from the root of your subdomain.

I agree on "Yosemite and later though". I'll make that fix.
